prompt = '> '
padding = 200
fonts = [ 'Berkeley Mono Semibold' ]
font_size = 20

[history]
decrease_interval = 48

[colors]
background = '#232A2E'
prompt = '#F8F9E8'
text_query = '#F8F9E8'
text = '#839E9A'      # for search results
text_selected= '#F8F9E8'# for the currently selected result

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["Delete", "BackSpace"]
delete_word = ["ctrl+w"]
complete = ["Tab"]
nav_up = ["ctrl+p", "Up"]
nav_down = ["ctrl+n", "Down"]
exit = ["ctrl+c", "Escape"]
