prompt = '> '
padding = 200
fonts = [ 'Berkeley Mono' ]
font_size = 20

[history]
decrease_interval = 48

[colors]
background = '#282828'
prompt = '#d4be98'
text = '#7c6f64'          # for search results
text_query = '#d4be98'
text_selected = '#ddc7a1' # for the currently selected result

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["Delete", "BackSpace"]
delete_word = ["ctrl+w"]
complete = ["Tab"]
nav_up = ["ctrl+p", "Up"]
nav_down = ["ctrl+n", "Down"]
exit = ["ctrl+c", "Escape"]
