prompt = '> '
padding = 200
fonts = [ 'Berkeley Mono Semibold' ]
font_size = 20

[history]
decrease_interval = 48

[colors]
background = '#2d353b'
prompt = '#d3c6aa'
text_query = '#d3c6aa'
text = '#56635f'      # for search results
text_selected= '#d3c6aa'# for the currently selected result

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["Delete", "BackSpace"]
delete_word = ["ctrl+w"]
complete = ["Tab"]
nav_up = ["ctrl+p", "Up"]
nav_down = ["ctrl+n", "Down"]
exit = ["ctrl+c", "Escape"]
