prompt = '> '
padding = 200
fonts = [ 'JetbrainsMono Nerd Font' ]
font_size = 20

[history]
decrease_interval = 48

[colors]
background = '#1C1C1C'
prompt = '#e0def4'
text = '#908CAA'      # for search results
text_query = '#e0def4'
text_selected = '#ebbcba'# for the currently selected result

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["Delete", "BackSpace"]
delete_word = ["ctrl+w"]
complete = ["Tab"]
nav_up = ["ctrl+p", "Up"]
nav_down = ["ctrl+n", "Down"]
exit = ["ctrl+c", "Escape"]
