live_config_reload = true

[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 14.0

[font.normal]
family = "Iosevka Fixed SS04 Md Ex"

[scrolling]
history = 4000

[shell]
program = "/usr/bin/zsh"
