live_config_reload = true


[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 14.0

[font.normal]
family = "Berkeley Mono"

[scrolling]
history = 4000

[shell]
program = "/usr/bin/zsh"
