[window]
dynamic_padding = true

[colors.primary]
background = "0x282828"
foreground = "0xddc7a1"

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 13.5

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "semibold"

[scrolling]
history = 4000

[general]
live_config_reload = true

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
